### ISSUE TITLE
Cleaned McNyset temperature data

### ISSUE THREAD

**Issue by mackerman44** [rcarmichael3/mra_redds_norwest#1]
I cleaned up some results shapefiles with modeled temperature results from the McNyset et al. model. It's all contained within mra_redds_norwest/data/mcnyset/temp. I then did a fair amount of cleaning of that data all in analysis/mcnyset_temp_prep.R and wrote out the results in a single shapefile data/mcnyset_temp/salmon_mcnyset_sf.shp.

Is this something you guys would find useful? Kevin, maybe you've already done some of that work in the past.

The data contained 3 years of 8-day mean results for Lemhi and the rest is 8-day max (3 years for Lemhi, 2 for Pahs, 2 for Upper Salmon). which is which is captured in the variable column in the cleaned dataset. Kevin - you and I had separate 8-day mean results for the Lemhi, which seemed to have some differences, but I didn't dig into those differences much, yet.

Alternatively, in a case like this, I wonder if it's worthwhile to just start storing all of our temperature data in a separate, new repository like "abs_temperature"? Might include all Norwest data, mcnyset data, tidbit data, and then cleaned datasets could always just be read in from there.

**Comment by rcarmichael3** [comment]
Mike, I think it might be a good idea to house temperature data in a separate repo as you suggested. I think I fixed the issue with the GIT ignore and you should be able to access the Pahsimeroi, Lemhi, and Upper Salmon mainstem Norwest temps that I used for the script. Let me know if the fix did not work and I will look into it further.

**Comment by mackerman44** [comment]
Hmm. it didn't appear to work. I doesn't look like you made any commits to the repo. After changing the .gitignore file did you commit and push those changes to the repo? And make sure the .gitignore file only lists those data files that are too big and you really don't want to push up. Thanks!

**Comment by rcarmichael3** [comment]
I committed and pushed the changes. I also edited the .txt file to only include the large shapefile from Norwest rather than the entire directory. My guess is that it is taking some time to reach you halfway around the world...hopefully that is only the problem and not something I am messing up.

**Comment by KevinSee** [comment]
I just pulled down the latest, and didn't see any norwest data. I do see "data/norwest/" listed in the .gitignore, so maybe your changes just haven't reached the western hemisphere yet Richie. I'll try again later.

**Comment by rcarmichael3** [comment]
Okay, the gitignore should say "data/norwest/NorWeST_temps.dbf so hopefully it shows up!

**Comment by mackerman44** [comment]
Right on, I'll check back in a bit. One thing I've run into recently is problems trying to do push/pulls on my Merck machine when off the Merck network...something about the proxy server. But I'm guessing you're working off your other machine?

**Comment by rcarmichael3** [comment]
Yeah, I am working on the Biomark computer. I have been lugging around two laptops and 4 external harddrives. Needless to say I have been stopped and searched in every single airport security check point. They don't like the stacked hard drives and all of the charging cables haha

**Comment by mackerman44** [comment]
Still no luck being able to get those Norwest shapefiles. As a temp fix, would you mind trying to e-mail me the Lemhi_norw.shp, Pah_nor.shp, and Salmon_norw.shp shapefiles? Please send to both my @biomark and @merck e-mails. We can figure out the problem after you get back.

Hope you're sneaking in some fun time!

**Comment by mackerman44** [comment]
Data just came through and pulled down to my machine. Thanks Richie!

**Comment by mackerman44** [comment]
Hey Guys -

Sorry to complicate things, but I went ahead and re-organized the temperature data in the repo. The McNyset data was moved from data/mcnyset_temp/ to data/temperature/mcnyset/ and the Norwest temp data was moved from data/norwest/ to data/temperature/norwest/.

This shouldn't affect Kevin and all, but Richie will need to move data/norwest/NorWeST_temps.dbf to data/temperature/norwest/Norwest_temps.df. Richie, my easiest suggestion would be to 
1. Move NorWeST_temps.dbf out of the repo
2. Delete the entire repo from your C: drive
3. Re-clone the repo, again
4. Move NorWeST_temps.dbf into the data/temperature/norwest/ directory that you will have after re-cloning. Then you should be good to go!

There is 0 rush on that, and I can help you do it quick after you're back in town (or do it for you). Just being anal about data and directory structures.
